name: weather
description: "by Ana Gallego"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  google_places_autocomplete_text_field: ^0.1.3
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  oktoast: ^3.4.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/weather/
    - assets/images/
